
modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"
showAsDataPack = true

[[mods]]
modId = "hygrave"
version = "2.1.1"
displayName = "HyperGrave"
description = "A very high-quality, customizable, sophisticated and simple-to-use grave mod"
logoFile = "pack.png"
authors = "Sul4ur"
displayURL = "https://modrinth.com/datapack/hypergrave"

[[dependencies.hygrave]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5, 26.2.999999]"
ordering = "NONE"
side = "BOTH"

[[dependencies.hygrave]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"
